// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataModel.Migrations
{
    [DbContext(typeof(LottoDbContext))]
    [Migration("20191022082614_AddedBonusTable")]
    partial class AddedBonusTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataModel.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int>("Gender");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password");

                    b.Property<byte[]>("Request");

                    b.Property<string>("State");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new { Id = 1, Age = 0, DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Gender = 0, Password = "a@???G??3-?<?Y?o", UserName = "JohnDoe" }
                    );
                });

            modelBuilder.Entity("DataModel.Bonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Award");

                    b.Property<DateTime>("Expiration");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("DataModel.LottoSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("AdminId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("TotalTickets");

                    b.Property<string>("WinningNumbers");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DataModel.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Numbers");

                    b.Property<int?>("Prize");

                    b.Property<int>("SessionId");

                    b.Property<int>("UserId");

                    b.Property<bool>("Win");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DataModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int>("Balance");

                    b.Property<string>("CardHolder");

                    b.Property<int>("CardNumber");

                    b.Property<string>("CardPassword");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int>("Gender");

                    b.Property<bool>("IsAccountConfirmed");

                    b.Property<bool>("IsSubscribed");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password");

                    b.Property<string>("State");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Age = 0, Balance = 0, CardNumber = 0, DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Gender = 0, IsAccountConfirmed = false, IsSubscribed = false, Password = "&l?:?? @???S???", UserName = "BobBobsky@yahoo.com" }
                    );
                });

            modelBuilder.Entity("DataModel.Bonus", b =>
                {
                    b.HasOne("DataModel.User", "User")
                        .WithMany("Bonuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.LottoSession", b =>
                {
                    b.HasOne("DataModel.Admin", "Admin")
                        .WithMany("Sessions")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Ticket", b =>
                {
                    b.HasOne("DataModel.LottoSession", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
